---
- name: installing application
  hosts: all
  gather_facts: yes
  become: true

  tasks:
    - name: installing httpd on rhel
      yum:
        name: httpd
        state: installed
      when: ansible_os_family == "RedHat"

    - name: starting httpd service on rhel
      service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"

    - name: install httpd on ubuntu
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: starting httpd service on ubuntu
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"

    - name: copy index.html file
      copy:
        src: /home/ansadmin/playbooks/index.html
        dest: /var/www/html
