---
- name: install httpd/apache2 on servers
  hosts: all
  become: true
  gather_facts: yes

  tasks:
  - name: install httpd on RedHat servers
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"

  - name: install apache2 on Debian servers
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    notify: starting httpd services

  - name: copy httpd file to target servers
    copy:
      src: /home/ansadmin/playbooks/index.html
      dest: /var/www/html

  handlers:
    - name: starting httpd services
      service:
        name: httpd
        state: started

    - name: starting apache2 service on Ubuntu servers
      service:
        name: apache2
        state: started
