---
- name: install multiple packages
  hosts: all
  become: true
  gather_facts: yes

  tasks:
  - name: installing packages
    yum:
      name: "{{ item.pkg }}"
      state: "{{ item.setup }}"
    loop:
     - {pkg: 'git', setup: 'latest'}
     - {pkg: 'make', setup: 'installed'}
     - {pkg: 'tree', setup: 'installed'}
     - {pkg: 'wget', setup: 'installed'}
